# -*- coding: utf-8 -*-
"""ex2.ipynb のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1poY01bZ-n7_6O0t_b_RrkXxi7znbSM52

# 第2回本課題

[English version](https://colab.research.google.com/drive/1Zgt3eNFWZF4mtfW3cjK4UqCvrbmcjVZ0)

## Ex2-1. 演算子の計算

`[('+', 3), ('-', 5), ('+', 2), ('+', 1), ('-', 10)]` のように、
演算子の文字列（`+` または `-`）と整数からなるタプルを格納したリスト `lp` が与えられたとき、
初期値 `0` に対して、リストの各タプルの演算子と整数を順に適用して得られる結果を返す関数
`calculate_ops(lp)` を定義して下さい。

たとえば、`lp` が上の例の場合、`calculate_ops(lp)` は `0+3-5+2+1-10` の計算結果を返します。
"""

##########################################################
##  <[ ex2-1-calculate_ops ]> 解答セル (Answer cell)
##  このセルの複製・削除を禁ず (Neither copy nor delete this cell)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

def calculate_ops(lp):
    result = 0
    for i in lp:
      if i[0] == '+':
        result += i[1]
      else:
        result -= i[1]
    return result

"""提出前に以下のテストセルを実行し、エラーがでないことを確認してください。"""

assert calculate_ops([('+', 3), ('-', 5), ('+', 2), ('+', 1), ('-', 10)]) == -9
assert calculate_ops([('-', 1), ('-', 2), ('-', 3)]) == -6
assert calculate_ops([('+', 1), ('+', 2), ('+', 3)]) == 6
assert calculate_ops([]) == 0

