# -*- coding: utf-8 -*-
"""lab1.ipynb のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rR-sbBljSPsm-gDSH__jyDv2grNzI-K4

### 問1
引数に与えられたリストの要素の値の標準偏差を返す関数`my_std`を実装してください。
"""

# 関数my_mean
def my_mean(L):
	s = 0
	for x in L:
		s = s + x
	return s / len(L)

def my_std(list):
  s = 0
  mean = my_mean(list)
  for i in list:
    s += (i - mean) ** 2
  return ((s/len(list)) ** 0.5)

my_std([1,2,3,4,5])

"""### 問2
組み込み関数の`sorted`にリストを与えると、リストの要素を昇順に並び替えた新たなリストを返します。

引数に与えられたリストの要素の値の中央値を返す関数`my_median`を実装してください。

"""

def my_median(list):
  new_list = sorted(list)
  n = len(list)
  if n % 2 == 0:
    mid1 = new_list[n // 2 - 1]
    mid2 = new_list[n // 2]
    return (mid1 + mid2) / 2
  else:
    return list[len(list) // 2]

my_median([5,4,3,2,1,10])