# -*- coding: utf-8 -*-
"""Python_basics のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9TM1T0dYCPJAgV3UnYfyi6NTGl_f2VU
"""

# コード1
5 + 3 # 1たす1

# コード2
8 - 4 # 1ひく1

# コード3
4 * 6 # 4かける6

# コード4
24 / 5 # 24わる5

# コード5
24 // 5 # 24わる5の商

# コード6
24 % 5 # 24わる5の余り

# コード7
2 ** 10 # 2の10乗

# コード8
1 + 1

# コード9
1 + 1.0

# コード10
1 + 1 == 1 + 1.0

# コード11
2 ** 100

# コード12
2.0 ** 1000

# コード13
2.0 ** -1000

# コード14
4 - 3 * 2

# コード15
(4 - 3) * 2

# コード16
+1

# コード17
-1

# コード18
5 + 3 - 6 * 4 / 2 ** 3 ** 1

# コード19
x = 5 + 3

# コード20
x + 1

# コード21
x = 5
x + 1

# コード22
x = 5
x = 5 + 3

# コード23
def addition(x, y):
	return x + y

# コード24
2 * addition(2, 5 - 3)

# コード25
def pythagorean(a, b):
	c = a ** 2 + b ** 2
	return c ** 0.5

# コード26
x = 10
y = 20
z = 30
print(x, y, z)

# コード27
x = 10
x > 0

# コード28
x = 20
y = 10
x == y

# コード29
x >= y

# コード 30
x = 30
y = 20
z = 10
x > y and x > z

# コード31
def maximum(x, y, z):
	if x > y and x > z:
		return x
	elif y > z:
		return y
	else:
		return z

# コード32
digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# コード33
empty_lst = []

# コード34
1 in digits

# コード35
lst = [10, 20, 30, 40, 50]
lst[1]

# コード36
lst.index(20)

# コード37
lst[-1]

# コード38
lst[1 + 1]

# コード39
len(lst)

# コード40
lst[1:4]

# コード41
lst[:3]

# コード42
lst[3:]

# コード43
lst[2] = 0

# コード44
lst.append(60)

# コード45
lsts = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

lst

# コード46
lsts[0]

# コード47
lsts[0][1]

# コード48
tpl = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

# コード49
empty_tpl = ()

# コード50
sol = (1,)

# コード51
tpl[1]

# コード52
tpl[2:3]

# コード53
word = 'Programming'

# コード54
word[0]

# コード55
word[0:7]

# コード56
blank = ''

# コード57
len(word)

# コード58
word = 'データ' + '解析'

# コード59
'apple' == 'Apple'

# コード60
'apple' < 'banana'

# コード61
'Program' in 'Programming'

# コード62
word = 'supercalifragilisticexpialidocious'
word.count('li')

# コード63
lst = [1, 2, 3, 4, 5]
s = 0
for x in lst:
	s = s + x
print(s)

# コード64
lst = [1, 2, 3, 4, 5]
for i, x in enumerate(lst):
	print(i, x)

# コード65
s = 0
n = 10
for x in range(1, n+1):
	s = s + x
print(s)

# コード66
lst = [1, 2, 3, 4, 5]
s = 0
for i in range(len(lst)):
	s = s + lst[i]
print(s)

# コード67
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
s = 0
for i in range(len(lst)):
	for j in range(len(lst[i])):
		s = s + lst[i][j]
print(s)

# コード68
dic = {'name' : 'Tom', 'age' : 60, 'country' : 'USA'}

# コード69
empty_dic = {}

# コード70
dic['name']

# コード71
'city' in dic

# コード72
dic['age'] = dic['age'] + 1

# コード73
dic['city'] = 'NY'

dic

# コード74
for k in dic.keys():
	print(k, dic[k])

# コード75
for k, v in dic.items():
	print(k, v)

# 関数my_mean
def my_mean(L):
	s = 0
	for x in L:
		s = s + x
	return s / len(L)

# 関数my_variance
def my_variance(L):
	s = 0
	mean = my_mean(L)
	for x in L:
		s = s + (x - mean) ** 2
	return s / len(L)

# 関数my_max
def my_max(L):
	m = L[0]
	for i in range(1, len(L)):
		if L[i] > m:
			m = L[i]
	return m

# 関数my_min
def my_min(L):
	m = L[0]
	for i in range(1, len(L)):
		if L[i] < m:
			m = L[i]
	return m

# 関数my_describe
def my_describe(L):
	return {
		'mean' : my_mean(L),
		'variance' : my_variance(L),
		'max' : my_max(L),
		'min' : my_min(L)
	}

# コード76
data = [2, 5, 4, 3, 6, 1, 7, 0, 9, 8]
my_describe(data)

# コード77
import pandas as pd
URL = 'https://www.nstac.go.jp/sys/files/SSDSE-E-2022v2.csv'
df = pd.read_csv(URL, skiprows=[0,1,3], encoding='shift_jis')
population_data = df['総人口'].tolist()

my_describe(population_data)

