# -*- coding: utf-8 -*-
"""ex4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-DeCe4iVRWxHNueOk5oHqWJFX0DYR36

# 第4回本課題

[English version](https://colab.research.google.com/drive/16KDKFStlf09UQjoyr_GXbfso_SWvwqNL)

## Ex4-1. イテラブルの分割

イテラブル（たとえばリスト）`xs` とデータ `y` を受け取って、
`xs` の要素の並びを `y` を区切りとして分割し、分割した要素を格納したリストのリストを返す関数
`split_iterable(xs,y)` を定義してください。
たとえば、

* `split_iterable([1,2,0,3,4,5,0], 0)` は `[[1, 2], [3, 4, 5], []]` を返します。
* `split_iterable('/ab/c/def', '/')` は、`[[], ['a', 'b'], ['c'], ['d', 'e', 'f']]` を返します。
* `split_iterable([], 0)` は `[[]]` を返します。

`split_iterable` は様々な種類のイテラブルを受け付けますが、
返値は必ずリストのリストになることに注意してください。

ファイルオブジェクトもイテラブルですので、`xs` がファイルオブジェクトである場合も動作するようにしてください。
たとえば、`xs` がファイルオブジェクトで、
`y` が文字列 `'\n'` であるとき、
`xs` の中の行は空白行を区切りとして分割され、空でない行のリストのリストが返されます。
"""

##########################################################
##  <[ ex4-1-split_iterable ]> 解答セル (Answer cell)
##  このセルの複製・削除を禁ず (Neither copy nor delete this cell)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

def split_iterable(xs,y):
    result = [[]]
    for i in xs:
      if i == y:
        result.append([])
      else:
        result[-1].append(i)
    return result

"""提出前に以下のテストセルを実行し、エラーがでないことを確認してください。"""

assert split_iterable([1,2,0,3,4,5,0], 0) == [[1, 2], [3, 4, 5], []]
assert split_iterable([], 0) == [[]]
with open('gokigenyou.txt', 'w', encoding='utf-8') as f:
    f.write('こんにちは。\nごきげんよう。\n\nさようなら。\n')
try:
    with open('gokigenyou.txt', 'r', encoding='utf-8') as f:
        assert split_iterable(f, '\n') == [['こんにちは。\n', 'ごきげんよう。\n'], ['さようなら。\n']]
finally:
    import os, contextlib
    with contextlib.suppress(IOError):
        os.remove('gokigenyou.txt')

