# -*- coding: utf-8 -*-
"""pre1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z2g3O6wWCELedgGTa_zuG9l4g8sZHeMM

# 第1回予習課題

[English version](https://colab.research.google.com/drive/18iJcFolCna-7EE6_M5Nan5LxJAU-DIaD)

## Pre1-1. mod inv
フェルマーの小定理によれば、$p$ を素数、$a$ を $0<a<p$ を満たす整数とすると、
次の合同式が成り立ちます。$$a^{p-1} \equiv 1~({\rm mod}~p)$$

$p$ と $a$ を受け取って $a^{p-2}$ を $p$ で割った余りを返す関数 `mod_inv(p,a)` を定義してください。
"""

##########################################################
##  <[ pre1-1-mod_inv ]> 解答セル (Answer cell)
##  このセルの複製・削除を禁ず (Neither copy nor delete this cell)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

def mod_inv(p,a):
  return a ** (p - 2) % p

"""提出前に以下のテストセルを実行し、エラーがでないことを確認してください。"""

assert mod_inv(13,5) == 8
assert mod_inv(13,5)*5 % 13 == 1
assert mod_inv(113,7)*7 % 113 == 1

"""## Pre1-2. 三角形の成立条件
3つの正数$a$, $b$, $c$を3辺の長さとする三角形が存在するための必要十分条件は以下の不等式で表されます。

$a<b+c$ かつ $b<c+a$ かつ $c<a+b$

3辺の長さ `a`, `b`, `c` をもらって、3辺が三角形を構成するならば `True`、そうでなければ `False` を返す `is_triangle(a,b,c)` という関数を定義してください。

以下のセルの `...` のところを書き換えてください。
"""

##########################################################
##  <[ pre1-2-is_triangle ]> 解答セル (Answer cell)
##  このセルの複製・削除を禁ず (Neither copy nor delete this cell)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

def is_triangle(a, b, c):
    if a < b + c and b < c + a and c < a + b:
      return True
    else:
      return False

"""提出前に以下のテストセルを実行し、エラーがでないことを確認してください。"""

assert is_triangle(3,3,3)
assert is_triangle(3,4,5)
assert not is_triangle(1,2,3)
assert not is_triangle(1,1,2)

