# -*- coding: utf-8 -*-
"""pre3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCSEC3LAPiuQnB2GsyhtKhO1WVAGvinD

# 第3回予習課題

[English version](https://colab.research.google.com/drive/1o0Ojufimqr0B0CuT2txep21UzyONLBT6)

## Pre3-1. 最初と最後の負数

与えられた数のリストの、最初の負数と最後の負数をタプルにして返す関数 `first_last_negative` を定義してください。
与えられた数には必ず負数が含まれると仮定して構いません。
"""

##########################################################
##  <[ pre3-1-first_last_negative ]> 解答セル (Answer cell)
##  このセルの複製・削除を禁ず (Neither copy nor delete this cell)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

def first_last_negative(ln):
  first = ln[0]
  second = ln[-1]
  for i in range(len(ln)):
    if ln[i] < 0:
      first = ln[i]
      break
  for i in reversed(range(len(ln) - 1)):
    if ln[i] < 0:
      second = ln[i]
      break
  return (first, second)

def first_last_negative2(ln):
  first = None
  last = None

  for i in ln:
    if i < 0:
      if first == None:
        first = i
      last = i
  return (first, last)

"""提出前に以下のテストセルを実行し、エラーがでないことを確認してください。"""

assert first_last_negative([0,1,2,-3,-4,5,6,-7,-8,9,10]) == (-3,-8)
assert first_last_negative([-3]) == (-3,-3)

assert first_last_negative2([0,1,2,-3,-4,5,6,-7,-8,9,10]) == (-3,-8)
assert first_last_negative2([-3]) == (-3,-3)

"""## Pre3-2. 文字列と辞書

文字列 `s` と 辞書 `d` が与えられたとき、
`s` の各文字 `c` を見ていって、`c` が `d` のキーとして登録されていたら、
辞書 `d` の中のキー `c` の値を 1 増やす関数 `inc_freq(s, d)` を定義してください。
（`d` に新たなキーを登録してはいけません。）

この関数は、引数の辞書の中身を関数内部で更新します。
返り値を返す必要はありません。
"""

##########################################################
##  <[ pre3-2-inc_freq ]> 解答セル (Answer cell)
##  このセルの複製・削除を禁ず (Neither copy nor delete this cell)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

def inc_freq(s, d):
  for i in range(len(s)):
    if s[i] in d.keys():
      d[s[i]] += 1
  return d

"""提出前に以下のテストセルを実行し、エラーがでないことを確認してください。"""

d = {'a':0, 'e':1, 's': 2, '.':3}
inc_freq('Is this a pen?',d)
assert d == {'a':1, 'e':2, 's': 4, '.':3}
inc_freq('Hello.',d)
assert d == {'a':1, 'e':3, 's': 4, '.':4}

